name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: ['1', '2', '3', '4', '5', '6', '7', '8']

    steps:
      - uses: actions/checkout@v4

      - name: Make script executable
        run: |
         mv ${{ matrix.build_type }}.txt repos.txt
         chmod +x build.sh
         ls

      - name: Run build
        run: bash build.sh

      - name: Generate checksum
        run: |
          cd /home/runner/work/ocioz/ocioz/ocio_output
          sha256sum *.ocioz > ${{ matrix.build_type }}.ocioz.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ocioz-${{ matrix.build_type }}
          path: |
            /home/runner/work/ocioz/ocioz/ocio_output/*.ocioz
            /home/runner/work/ocioz/ocioz/ocio_output/*.ocioz.sha256

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Generate checksum
        run: |
          cd artifacts
          cat **/*.ocioz.sha256 > ocioz.sha256
          rm **/*.ocioz.sha256

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: PixelManager
          name: PixelManager Rolling Release
          prerelease: true
          files: artifacts/**/*
